services:
  # Next.js Frontend
  client:
    build: 
      context: ./client  # ← Add this
      dockerfile: Dockerfile
    ports:
      - "3001:3000"
    environment:
      - NODE_ENV=production
    networks:
      - portfolio-network

  # Node.js Backend API
  api:
    build: 
      context: ./server  # ← Add this
      dockerfile: Dockerfile
    ports:
      - "5050:5050"
    environment:
      - NODE_ENV=production
      - ATLAS_URI=${ATLAS_URI}
    env_file:
      - ./server/config.env
    networks:
      - portfolio-network

  # Nginx Reverse Proxy
  nginx:
    build: 
      context: ./nginx  # ← Add this
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - client
      - api
    networks:
      - portfolio-network

networks:
  portfolio-network:
    driver: bridge